name: Deploy Phaser Application

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./04_actions

    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm run build
        working-directory: ${{ env.working-directory }}
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ${{ env.working-directory }}/dist
